name: update-githu-secret
description: "This action creates a new github actions secret or updates an existing one."
author: 'Charles Boadu Jr'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'lock'  
  color: 'purple'
